# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-03 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20160602_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporter',
            name='address',
            field=models.CharField(default=6666, max_length=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reporter',
            name='email',
            field=models.CharField(default=7777, max_length=70),
            preserve_default=False,
        ),
    ]
