# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-03 06:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20160603_0632'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporter',
            name='create_data',
            field=models.DateField(default=datetime.datetime(2016, 6, 3, 6, 38, 46, 847039, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
