# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-03 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_reporter_create_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporter',
            name='create_data',
            field=models.DateTimeField(),
        ),
    ]
